### ISSUE TITLE
Rate limiting issue?

### ISSUE THREAD

**Issue by JVT038** [wasi-master/sponsorblock.py#2]
Hi,
So overall I'm really satisfied with this library, as it does everything I want.
However, I occasionally get this exception and can't figure out why.
`
HTTPSConnectionPool(host='sponsor.ajay.app', port=443): Max retries exceeded with url: /api/skipSegments?videoID=gxEPV4kolz0&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=preview&category=music_offtopic&category=poi_highlight&service=YouTube (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CFA622A310>: Failed to establish a new connection: [WinError 10060] Een verbindingspoging is mislukt omdat de verbonden party niet correct heeft geantwoord na een bepaalde tijd, of de gemaakte verbinding is mislukt omdat de verbonden host niet heeft geantwoord'))
`
The WinError 10060 says: "An attempt to connect has failed, because the connected party answered incorrectly after a certain time, or the made connection has failed because the connected host hasn't answered'".

Does sponsorblock has a rate limit? If yes, how do I work around it (a `sleep()` function perhaps) to prevent this?

**Comment by wasi-master** [comment]
If the request could not happen because of a ratelimit then the library would've raised a [RateLimiException](https://sponsorblockpy.readthedocs.io/en/latest/api_reference.html#sponsorblock.errors.RateLimitException). But since it didn't I guess this isn't a ratelimit.

Looks like there is a network issue between your PC and the server. Perhaps firewall or proxy settings? Or maybe the server was down? Or maybe the server blocked the request (low chance)? Or maybe your PC just didn't have an internet connection when that error occured

Since the error is occasional I assume this doesn't happen always.
And there are ratelimits only for creating new segments. Although you still shouldn't spam
> While this is a free unlimited use API, please don't abuse it. I have limited resources.

**Comment by ajayyy** [comment]
This is not a ratelimit, but a server issue we are dealing with. Haven't found a solution yet unfortunately

**Comment by wasi-master** [comment]
@JVT038 So there's your answer...
